# Generated by Django 3.0.5 on 2024-01-19 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20240120_0116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('logo', models.ImageField(upload_to='mediafile', verbose_name='Logo')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('address_id', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('establishment', models.DateField()),
                ('degrees', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payments_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'unpaid')], max_length=255, null=True)),
                ('insurance_company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.InsuranceCompany')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('request_status', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Wait', 'Wait'), ('Paid', 'Paid')], max_length=255, null=True)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.InsuranceCompany')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('name_company', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ex_subscription', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Men'), ('Female', 'Female')], max_length=255, null=True)),
                ('blood', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.TextField()),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Address')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
