# Generated by Django 3.0.5 on 2024-01-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20240120_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecompany',
            name='degrees',
        ),
        migrations.AddField(
            model_name='users',
            name='degrees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
