# Generated by Django 3.0.5 on 2024-01-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_medicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='allergeis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='considerations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='current_madications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='family_medical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='lifestyle_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='special',
            field=models.TextField(blank=True, null=True),
        ),
    ]
