# Generated by Django 3.0.5 on 2024-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20240120_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='degrees',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='degrees',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=255, null=True),
        ),
    ]
