# Generated by Django 3.0.5 on 2024-01-25 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_company', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_degree', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company'), ('family', 'Family')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TameenakCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(default='image/tameenak_user/profile_pic/default_pic.png', upload_to='image/tameenak_user/profile_pic/')),
                ('ex_subscription', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_status', models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('blood', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tameenak_user.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('reject', 'Reject'), ('waiting', 'Waiting'), ('paid', 'Paid')], max_length=100, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('request_date', models.DateField(auto_now=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_company.InsuranceCompany')),
                ('insurance_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tameenak_user.InsuranceDegree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tameenak_user.TameenakCustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
