# Generated by Django 3.0.5 on 2024-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tameenak_user', '0002_auto_20240203_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tameenakcustomer',
            name='picture',
            field=models.ImageField(default='image/tameenak_user/default_pic.png', upload_to='image/tameenak_user/tameenak_customer/profile_pic/'),
        ),
    ]
