# Generated by Django 3.0.5 on 2024-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='tameenak_user',
            new_name='customer',
        ),
    ]
